# -*- coding: utf-8 -*-
"""car-game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12ocxUr3eeQGGAVPlCH94wsHmE9n_xWPi
"""

import pygame
import sys
# Define some colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
# Initialize the game engine
pygame.init()
# Set the window size
screen = pygame.display.set_mode((800, 600))
# Create a clock to track time
clock = pygame.time.Clock()
# Create a car sprite
car = pygame.sprite.Sprite()
car.image = pygame.Surface((40, 40))
car.image.fill(RED)
car.rect = car.image.get_rect()
car.rect.center = (400, 300)
# Create a group of all sprites
all_sprites = pygame.sprite.Group()
all_sprites.add(car)
# Game loop
while True:
    # Check for events
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            sys.exit()
    # Update the game state
    car.update()
    # Draw the game画面
    screen.fill(BLACK)
    all_sprites.draw(screen)
    # Flip the display
    pygame.display.flip()
    # Cap the frame rate at 60 FPS
    clock.tick(60)